### ISSUE TITLE
CPLEX Distance variable naming

### ISSUE THREAD

**Issue by npeschke** [saezlab/CARNIVAL-Bioconductor-Dev#5]
This code will take the node names without checking for compliance with CPLEX naming conventions.
https://github.com/saezlab/CARNIVAL-Bioconductor-Dev/blob/4a7c93ccb6444788c6b327bb50f731faa9295334/R/create_variables_all.R#L146-L147

https://www.ibm.com/support/knowledgecenter/SSSA5P_12.8.0/ilog.odms.cplex.help/CPLEX/FileFormats/topics/LP_VariableNames.html

Most importantly it does not account for a "-" character in the node names which is not permitted by CPLEX since it could be misunderstood for a arithmetic minus sign.

I was using cplex on a mouse PKN from omnipath (http://omnipathdb.org/interactions?genesymbols=1&organisms=10090). This includes proteins like 
`"Nkx3-1" "Nkx3-1" "Nkx3-1" "Nkx3-1" "H2-Ab1" "H2-Q10" "Hbb-b1" "H2-T23" "H2-T23" "H2-D1"  "H2-Q7"  "H2-K1"  "Nkx2-5" "Hbb-b1" "Nkx2-5" "Nkx3-1"`
Those are translated into lines similar to this one in the lp file:
`101 xb14238_1 + dist_Wwtr1 - dist_Nkx2-1 <= 100`
which results in the following CPLEX error:
`CPLEX> CPLEX Error  1616: Line 184237: Expected identifier, found '<'.`

Could the distance variable generation easily be changed to use the same style of variables like for the other nodes (the `xb1_2` etc. scheme) or does this have additional side effects down the line?

**Comment by npeschke** [comment]
Most likely this will also be an issue for the generation of the delta variables in the case of multiple perturbations

**Comment by enio23** [comment]
Node naming issue handled
